#!/bin/bash
# Algorithme de compilation du document.

source ._bash_common

declare -ar bibs=( rapport web )
needscmd clear
needscmd seq

touch rapport.ann # N'est plus défini après `clean`, ce qui ferait planter la compilation

declare -i etape=0

compilation() {
	let etape++
	clear
	echo "== Compilation #$etape =="
	cp rapport.ann annexes.tex
	"$@" || exit 1
}

compiler() {
	compilation pdflatex rapport
}

preCompiler() {
	compilation pdflatex '\def\rpModeBrouillon{}\input{rapport}'
}

# Lecture de la bibliographie
preCompiler

# Préparation de la bibliographie
for sousEtape in $( seq 1 ${#bibs[@]} )
do
	clear
	echo "== Compilation #$etape.$sousEtape =="
	bibtex "${bibs[$sousEtape-1]}"|| exit 1
	let sousEtape++
done

# Intégration de la bibliographie
# Géneration du sommaire
preCompiler

# Intégration du sommaire
compiler

rm annexes.tex
