#!/bin/bash

source ._bash_common

declare -a options=( "$@" )
declare -i derniereOption=$( expr $# - 1 )

needscmd seq

opt() {
	for i in $( seq 0 $derniereOption )
	do
		if [ "_${options[$i]}" = "_$1" ]
		then
			return 0
		fi
	done
	
	return 1
}

doIt() {
	if ! opt --quiet
	then
		echo "$@"
	fi
	"$@"
}

# Par défaut, * sans correspondance est conservé
# Cette option le remplace par une absence d'arguments
shopt -s nullglob

declare -a fichiers=( *.aux *.log *.lof *.ann *.toc *.bbl *.blg )

# Pas de gestion du document final par défaut
if opt --all && [ -f rapport.pdf ]
then
	fichiers+=( rapport.pdf )
fi

if [ "${#fichiers[@]}" -eq 0 ]
then
	exit 0
fi

if opt --tmp
then
	# Assurons-nous que le dossier existe
	noout mkdir tmp
	# Déplacement
	noout doIt mv "${fichiers[@]}" tmp
else
	noout doIt rm "${fichiers[@]}"
fi
