#!/bin/bash
# Exécuter `flags` pour la documentation.

source ._bash_common

declare -r simple=$( bool [ "_$1" = '_-s' ] )

IFS=','
noerrout cat ._flags.csv flags.csv | while read line
do
	fields=( $line )
	if $simple
	then
		printf '%s : ' "${fields[0]}"
	else
		printf '%s (%s) : ' "${fields[3]}" "${fields[0]}"
	fi
	if [ -f "${fields[2]}.mrp" ]
	then
		echo actif
	else
		echo inactif
	fi
done
